### ISSUE TITLE
Restrictive upper bounds

### ISSUE THREAD

**Issue by snoyberg** [isomorphism/these#11]
There's a request to add @chrisdone's shell-conduit package to Stackage, which depends on `these`. However, `these` has the following restrictive upper bounds:

- profunctors-4.2.0.1 -- >=3 && <4.1
- semigroupoids-4.2 -- >=1.0 && <4.1

Would it be possible to relax these upper bounds?

**Comment by isomorphism** [comment]
Sorry for not noticing this issue, I went a bit AWOL for a while last year due to other demands on my time.
