### ISSUE TITLE
Diffing aligned structures

### ISSUE THREAD

**Issue by endgame** [isomorphism/these#115]
Reflex provides a function [`Data.Map.Misc.diffMap :: (Ord k, Eq v) => Map k v -> Map k v -> Map k (Maybe v)`](https://hackage.haskell.org/package/reflex-0.6.1/docs/Data-Map-Misc.html#v:diffMap) which compares two `Map`s and returns a `Map` with all the updates.

Looking at its source, there is nothing `Map`-specific going on, and it could be generalised (using [`Filterable`](https://hackage.haskell.org/package/witherable-0.3.1/docs/Data-Witherable.html#t:Filterable) from `witherable`) to:
```haskell
diffAlign :: (Semialign f, Filterable f, Eq a) => f a -> f a -> f (Maybe a)
```

I want to write this and upload it somewhere. Reflex also provides a `diffMapNoEq` variant that assumes anything present in the second `Map` is an update. There is a third unwritten variant that is left-biased, and I'd like to write both of these too. Neither `filterable` nor `semialign` depend on each other, but `filterable`s dependency footprint is small (it would add one transitive dependency: `base-orphans`).

Would you accept a PR to add these functions and a dependency on `filterable`, or should I stand up a `semialign-diff` package?

**Comment by Ericson2314** [comment]
You definitely want to talk with @xplat. He has some very interesting ideas between these two packages, especially `Crosswalk`, `Witherable` and semigroupoid's [`Traversable1`](http://hackage.haskell.org/package/semigroupoids-5.3.2/docs/Data-Semigroup-Traversable.html).

**Comment by endgame** [comment]
I can't PR this package because `filterable` now transitively on `lens`. I've pushed https://github.com/qfpl/semialign-diff to play with these ideas.
