### ISSUE TITLE
Question: Why are This and These treated differently?

### ISSUE THREAD

**Issue by turion** [isomorphism/these#123]
https://github.com/isomorphism/these/blob/5cdee44edb3321e2b270a18e545cdd089321c253/these/src/Data/These.hs#L258

I was puzzled to see that `This a <*> This b == This a` and not `This $ a <> b`, but `These a f <> These b x = These (a <> b) $ f x`. Wouldn't it be more symmetric if `This` would also use the semigroup, or if `These` wouldn't? Also confusingly, `This a <*> This b /= This a <> This b`.

I can't really find an `Applicative` or `Monad` law this is breaking, or a proof that all laws hold (quite a bit of work with so many cases). But still I find it a noteworthy unexpected feature that might be good to document. What's the reason for this particular instance?

**Comment by phadej** [comment]
```diff
--- a/these/src/Data/These.hs
+++ b/these/src/Data/These.hs
@@ -255,7 +255,9 @@ instance Bitraversable These where
 
 instance (Semigroup a) => Applicative (These a) where
     pure = That
-    This  a   <*> _         = This a
+    This  a   <*> This b    = This (a <> b)
+    This  a   <*> That _    = This a
+    This  a   <*> These b _ = This (a <> b)
     That    _ <*> This  b   = This b
     That    f <*> That    x = That (f x)
     That    f <*> These b x = These b (f x)
```

resuls in `Monad` and `Applicative` instance not agreeing

```
      Monad
        right identity:                  OK
          +++ OK, passed 100 tests.
        left identity:                   OK
          +++ OK, passed 100 tests.
        composition:                     OK
          +++ OK, passed 100 tests.
        pure = return:                   OK
          +++ OK, passed 100 tests.
        (<*>) = ap:                      FAIL
          *** Failed! Falsified (after 5 tests and 6 shrinks):
          This (0 :| [])
          This (0 :| [])
          This (0 :| [0]) /= This (0 :| [])
          Use --quickcheck-replay=357019 to reproduce.
```

**Comment by turion** [comment]
Ah, so your argument is `This a <*> x == This a >>= const x == This a`. And of course there is no other possible implementation for `This a >>= f` than `This a` since `f :: b -> These a c`, and we cannot produce a `b` from `This a`. Makes sense, thanks!
