### ISSUE TITLE
NonEmptyMap can be aligned but not zipped

### ISSUE THREAD

**Issue by Ericson2314** [isomorphism/these#125]
NonEmptyMap is in http://hackage.haskell.org/package/non-empty/docs/Data-NonEmpty-Map.html, and hopefully soon in containers itself via https://github.com/haskell/containers/pull/616 if I may self-plug. We cannot zip two non empty maps because if they have no keys in common we must end up with an empty map. Put in SQL terms, we only have "outer join", not "inner join".

**Comment by phadej** [comment]
I have an idea, but having https://github.com/haskell/containers/pull/616 closer to merged state would motivate me more.

**Comment by phadej** [comment]
Resolved in https://hackage.haskell.org/package/semialign-1.1
