### ISSUE TITLE
theseFromMaybes

### ISSUE THREAD

**Issue by andrewthad** [isomorphism/these#13]
I just wrote this for a project at work. Not sure if other people need this often, but I figured it would be worth considering adding to the package:

    theseFromMaybes :: Maybe a -> Maybe b -> Maybe (These a b)
    theseFromMaybes Nothing Nothing = Nothing
    theseFromMaybes (Just a) Nothing = Just (This a)
    theseFromMaybes Nothing (Just b) = Just (That b)
    theseFromMaybes (Just a) (Just b) = Just (These a b)

**Comment by isomorphism** [comment]
Seems reasonable to me and I can't immediately think of a simple way to implement it in terms of other functions, so if it was useful to someone I'm more than happy to add it.

**Comment by andrewthad** [comment]
Sweet. Do you need me to put up a PR for this, or can you just add it from what I pasted?

**Comment by isomorphism** [comment]
Already on it. :]

**Comment by isomorphism** [comment]
Actually, hold up. Isn't this just the `Maybe` instance of `align`?

**Comment by isomorphism** [comment]
Yeah, it is:

    instance Align Maybe where
        nil = Nothing
        align Nothing Nothing = Nothing
        align (Just a) Nothing = Just (This a)
        align Nothing (Just b) = Just (That b)
        align (Just a) (Just b) = Just (These a b)

Not sure why I didn't realize that at first, whoops.

**Comment by andrewthad** [comment]
Ah, very clever. Now I understand what `Align` does. Thanks. You can close this issue then, but first I wanted to ask: Is there a functional pearl or an article somewhere that explains the motivation behind `Align` and `Chronicle`?

**Comment by isomorphism** [comment]
I don't think there's anything like that, and I'm not sure there's even that much to say about either of them.

`Chronicle` was basically just me trying to see what using `These` as a monad would be like. I've used it a couple times but there's really not much to it beyond the obvious. The silly function names I used are probably the most interesting part, heh.

On the other hand, `Align` has a clear motivation as what I call a "structural union". For some container-like `Functor`s, you can combine two values by lining up matching constructors and constructing a value either from the places where both inputs have a value (like zipping lists) or from the places where at least one of the inputs has a value, which is what `align` does. An intuitive example is that for two lists `xs` and `ys`, `length (zip xs ys)` = `min (length xs) (length ys)`, whereas `length (align xs ys)` = `max (length xs) (length ys)`. By analogy, you can think of `Maybe` as a "list" of zero or one items.

The other type classes in `Data.Align` don't have any particular use case that I recall, they just seemed reasonable additions to `Align`. (For a while, @ehird and I had some in-jokes about `Bicrosswalk` being an abstraction too perfect to ever actually use.)

**Comment by andrewthad** [comment]
Thanks for that description. That helps a lot.
