### ISSUE TITLE
failure to build on centos

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [isomorphism/these#145]
these-1.1.1 is failing to compile (as a dependency) on CentOS images using ghc-8.8.3 (and otherwise using a freeze file that matches stackage 16.5) with

```
Building library for these-1.1.1..

src/Data/Functor/These.hs:13:0: error:
     error: missing binary operator before token "("
     #elif MIN_VERSION_transformers(0,5,0)
     ^
   |
13 | #elif MIN_VERSION_transformers(0,5,0)
   | ^
```

which might possibly be related to the tooling available on that platform.

The only thing I can think of is maybe the empty newline on the previous line is rejected, somehow :man_shrugging:

**Comment by phadej** [comment]
that error happens when `MIN_VERSION_transformers` is not defined. That may happen, but with GHC-8.8.3 that conditional shouldn't be evaluated at all. Looks like the cpp implementation I run into are more resilient.

I guess your CentOS has some old GCC?

**Comment by symbiont-sam-halliday** [comment]
I'll look into this. I have a script to run cabal inside a docker image of any other OS that you might be interested in. Yes, a simple 50 line bash script can replace an entire `stack` feature! Who would have guessed?

https://gitlab.com/fommil/dotfiles/-/blob/master/bin/cabal-docker

FYI this is the more detailed error

```
src/Data/Functor/These.hs:13:0: error:
     error: missing binary operator before token "("
     #elif MIN_VERSION_transformers(0,5,0)
     ^
   |
13 | #elif MIN_VERSION_transformers(0,5,0)
   | ^

src/Data/Functor/These.hs:16:0: error:
     error: missing binary operator before token "("
     #elif MIN_VERSION_transformers_compat(0,5,0) && !MIN_VERSION_transformers(0,4,0)
     ^
   |
16 | #elif MIN_VERSION_transformers_compat(0,5,0) && !MIN_VERSION_transformers(0,4,0)
   | ^

src/Data/These.hs:11:0: error:
     error: missing binary operator before token "("
     #elif MIN_VERSION_transformers(0,5,0)
     ^
   |
11 | #elif MIN_VERSION_transformers(0,5,0)
   | ^

src/Data/These.hs:14:0: error:
     error: missing binary operator before token "("
     #elif MIN_VERSION_transformers_compat(0,5,0) && !MIN_VERSION_transformers(0,4,0)
     ^
   |
14 | #elif MIN_VERSION_transformers_compat(0,5,0) && !MIN_VERSION_transformers(0,4,0)
   | ^

src/Data/Functor/These.hs:1:1: error:
    `gcc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP                #-}
  | ^

src/Data/These.hs:1:1: error:
    `gcc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP                #-}
  | ^
```

**Comment by symbiont-sam-halliday** [comment]
ok, it looks like this version of `cpp` doesn't support the highly advanced language feature `#elif`

**Comment by phadej** [comment]
Made a release with a fix: https://hackage.haskell.org/package/these-1.1.1.1
