### ISSUE TITLE
non-clear use of `join` in the definition of laws

### ISSUE THREAD

**Issue by imz** [isomorphism/these#15]
<http://hackage.haskell.org/package/these-0.4.2/docs/Data-Align.html>:

     join align = fmap (join These)

whereas

    align :: f a -> f b -> f (These a b)

`join` is known as an operation for monads: `Monad m => m m a -> m a`.

I don't understand how this applies to `align`.

Could you please clarify this?

**Comment by phadej** [comment]
the `(->) r` is a `Monad` too, more often known as `Reader`.

```hs
join :: m (m a) -> m a` where `m = (->) r` is `join :: ((->) r) (((->) r) a) = r -> r -> a
```
For example:
```hs
> join (+) 4
8
```

I'm personally unaware if there is less general `(r -> r -> a) -> (r -> a)` function in Prelude.

**Comment by isomorphism** [comment]
Using `join` like that is admittedly a bit obtuse if you're not familiar with the idiom, heh. If there was a less general `(r -> r -> a) -> (r -> a)` I'd use that for clarity, but otherwise I think it's fine as-is.
