### ISSUE TITLE
Upper bounds

### ISSUE THREAD

**Issue by andrewthad** [isomorphism/these#16]
Could you bump the upper bounds (or remove them) to allow newer versions of these packages:

    bifunctors: needed (>=0.1 && <4.2), but 4.2.1 found
    profunctors: needed (>=3 && <4.1), but 4.4.1 found
    semigroupoids: needed (>=1.0 && <4.1), but 4.3 found
    semigroups: needed (>=0.8 && <0.16), but 0.16.2.2 found

**Comment by isomorphism** [comment]
The upper bounds now include all the aforementioned versions.
