### ISSUE TITLE
vector 0.11 upper bound missing on 0.4 and 0.4.1

### ISSUE THREAD

**Issue by bennofs** [isomorphism/these#20]
The versions 0.4 and 0.4.1 also need an upper bound on `vector <0.11`, since that version introduced changes that break these. 0.4.2 already has that bound, but the cabal solver will just choose `0.4` or `0.4.1` if they don't also get the bound. See http://matrix.hackage.haskell.org/package/these

**Comment by bergmark** [comment]
I published revisions for all versions < 0.4.2 to disallow vector-0.11. Queuing new matrix build.
