### ISSUE TITLE
Please add support for recent versions of vector

### ISSUE THREAD

**Issue by peti** [isomorphism/these#23]
After updating our package set in NixOS to the latest version of `vector`, we can no longer compile `these`: http://packdeps.haskellers.com/feed?needle=these.

**Comment by phadej** [comment]
Will be fixed as soon as https://github.com/isomorphism/these/pull/19 is landed

**Comment by peti** [comment]
Will you release a new version?

**Comment by jwiegley** [comment]
@peti I uploaded it to Hackage today as 0.6.0.0.
