### ISSUE TITLE
New release or revision.

### ISSUE THREAD

**Issue by phadej** [isomorphism/these#24]
I committed the change to the `these.cabal`, but as I'm not a Hackage maintainer, cannot do the upload / revision. Tests pass ok.

**Comment by phadej** [comment]
ping @isomorphism @jwiegley

**Comment by phadej** [comment]
Stackage issue for the record: https://github.com/fpco/stackage/issues/817

**Comment by isomorphism** [comment]
Does relaxing an upper bound like this generally warrant a new minor version or upload? I edited the 0.6.0.0 metadata on hackage but I'm not sure if that's the correct thing to do. John has done all the actually hackage uploads so far, so I'm kinda fuzzy on hackage guidelines :)

**Comment by phadej** [comment]
AFAIK either way work, when we want to allow more dependencies. Only revision will fix the issue, if we have too acceptive bounds, as the offending version could still be picked by a solver.

Revisions are relatively new feature, but people seems to use it.

This is ok now, thanks!

**Comment by jwiegley** [comment]
@isomorphism For things like this, just editing bounds does not require uploading a new release.
