### ISSUE TITLE
Turn on Travis-CI

### ISSUE THREAD

**Issue by sjakobi** [isomorphism/these#33]
@isomorphism: Can you turn on Travis-CI? The `.travis.yaml` already exists!

Here's a short guide: http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

**Comment by isomorphism** [comment]
Sure! I've never used it before, so I appreciate the link, heh. I'll take a look when I have time, probably sometime tonight.

**Comment by sjakobi** [comment]
Great! Simply follow points 1 and 2 and then push something to the repository.

For example, you could add a README.md containing the build status image. :)
```
[![Build Status](https://secure.travis-ci.org/isomorphism/these.svg)](http://travis-ci.org/isomorphism/these)
```

**Comment by isomorphism** [comment]
Mission accomplished! And there was much rejoicing.
