### ISSUE TITLE
Mention Align in the description

### ISSUE THREAD

**Issue by isomorphism** [isomorphism/these#34]
It occurred to me that `Align` is a significant use case--possibly the *most* significant use case--for `These`, but nothing in the package description and almost nothing outside of `Data.Align` even mentions it. 

Considering that variants on the question "how to zip with padding" come up semi-regularly on SO etc., this should probably be rectified so that `Align` gets more visibility.

**Comment by jwiegley** [comment]
Agreed, `Align` is pretty much the whole reason I use `these`.

**Comment by phadej** [comment]
New hackage shows README.md file, and as it seems there is README.md already. So this will be solved with the next upload?

**Comment by isomorphism** [comment]
@phadej As it happens, writing that README.md is what made me think about emphasizing `Align`!

At very least, `Align` and its purpose should get equal billing in the package synopsis along with `These` and `MonadChronicle`.

**Comment by isomorphism** [comment]
Ok, dropped the mention of `ChronicleT` and added a short description of `align`.
