### ISSUE TITLE
dmwit likes Data.Default

### ISSUE THREAD

**Issue by isomorphism** [isomorphism/these#35]
...and wants the type of `dictate` to be `(MonadChronicle c m, Default a) => c -> m a`, that is. (Bug reports regarding taste in type classes should be filed against @dmwit rather than `these`.)

Conversation on IRC starts [here](http://ircbrowse.net/browse/haskell?id=21438393&timestamp=1442353788#t1442353788) and continues [here](http://ircbrowse.net/browse/haskell?id=21438728&timestamp=1442356459#t1442356459).

For all that I consider the `Default` class to be rather dubious, after thinking about it this particular scenario does make sense in the context of using `MonadChronicle`. Not to mention that, as far as I know, making this change is supported by 100% of the people who actually use `MonadChronicle`. As such, I'm leaning toward making the change in some fashion, though I'd slightly prefer to add a new function rather than change the existing `dictate`.

It feels a bit silly to add a dependency on another package for just this one thing, but eh, not really a big deal.

I'll do something about this once I've finished self-bikeshedding over the name issue, creating this issue so I don't forget and in case anyone wants to offer opinions.

**Comment by phadej** [comment]
- I'm interested to know who use `MonadChronicle`, `reflex` doesn't seem to use it.
- If you add this, I'd add new function (say `dictateDef`) with the default implementation using `dictate`.
- I don't like `Default` type class either. Haven't found it that useful myself.

**Comment by isomorphism** [comment]
I've used it a couple times for simple things, but as indicated by the tongue-in-cheek "100% of users" remark, aside from @dmwit I don't know of anyone else.
