### ISSUE TITLE
these still has no docs on hackage

### ISSUE THREAD

**Issue by isomorphism** [isomorphism/these#36]
And no build reports, failed or otherwise.

What's up with that?

**Comment by phadej** [comment]
I asked about on IRC. We can upload the docs ourselves too.

**Comment by isomorphism** [comment]
Yeah, I was planning to look into that at some point here. I'd still like to know why it isn't being built by hackage, though.

**Comment by sjakobi** [comment]
[This blog post](http://begriffs.com/posts/2014-10-25-creating-package-hackage.html) contains a script for pushing docs to hackage at the end.

Others simply include a link to stackage in the "Summary" field of their cabal files.

Both ways are rather annoying workarounds though.

**Comment by sjakobi** [comment]
Actually, Neil Mitchell's [neil tool](https://github.com/ndmitchell/neil) may be more reliable then the bash script.

See [his blog](http://neilmitchell.blogspot.co.uk/2014/10/fixing-haddock-docs-on-hackage.html) for usage information.

**Comment by isomorphism** [comment]
Ok, I pre-emptively uploaded docs along with 0.6.1--thanks for the links &c. Gonna optimistically close this issue and hope that hackage just didn't like version 0.6 for some reason.
