### ISSUE TITLE
These -> NonEmpty?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [isomorphism/these#6]
I was using These to do a relational join on sorted lists:

[(a, b)] -> [(a, c)] -> [(a, These b c)]

But then to do a multi-way join, I needed this:

[[(a, b)]] -> [(a, NonEmpty b)]

Given that the first signature is the 'base case' for the latter, I think a function, something like:

These a a -> NonEmpty a

makes sense.

**Comment by isomorphism** [comment]
Since `these` depends on all the relevant packages for `bifold1` I'm ok with leaving it at that, though in general I'm willing to add specialized versions of generic functions given a convincing use-case and/or a clever name.
