### ISSUE TITLE
A seemingly illegal reference to `join` in the laws

### ISSUE THREAD

**Issue by deepfire** [isomorphism/these#73]
[Control.Monad.join](https://hackage.haskell.org/package/base-4.2.0.1/docs/Control-Monad.html#v%3Ajoin) (I take it..) is mentioned in the laws required of `Align` instances:
- https://github.com/isomorphism/these/blob/master/Data/Align.hs#L95

It seems illegal, since `Monad` isn't required for `Align`, and so the semantics are unclear.

(..to say nothing of the `Bifunctor` law..)

**Comment by phadej** [comment]
```haskell
Prelude Data.These Data.Align Control.Monad> :t join align
join align :: Align f => f b -> f (These b b)
Prelude Data.These Data.Align Control.Monad> :t fmap (join These)
fmap (join These) :: Functor f => f a -> f (These a a)
```

`join` is used there for `(->) a` monad.
```haskell
Prelude Data.These Data.Align Control.Monad> :t join :: (a -> a -> x) -> a -> x
join :: (a -> a -> x) -> a -> x :: (a -> a -> x) -> a -> x
```

I agree it's not the most clear way to stay that law, but it way more concise than alternatives. `bimap` is over `These`, not the functor we write `Align` instance for.

**Comment by phadej** [comment]
That said, if you can improve the comments, I'll more than happily accept the PR
