### ISSUE TITLE
Getting the this or that component of a These

### ISSUE THREAD

**Issue by maxigit** [isomorphism/these#86]
At, the moment, there is a few way to the get the this or that bit of a That or a This (ie `These a b -> Maybe a` and `These a b -> Maybe b`) but none of them works for a These : one could expect `fromThis (These "a" "b")` to return `Just "a"` but it returns instead `Nothing`. This somehow makes sense, but is counter intuitive if you see These as a super `(Maybe a, Maybe b)`. Moreover, unless I'm missing something, there is no simple way to get this behavior. The "simplest" I found is to use `unalign`.

**Comment by phadej** [comment]
I'm ok to adding `fromHere` and `fromThere` (`fromThis` implies that it uses only that constructor value).

**Comment by maxigit** [comment]
That'll be great. `justHere` and `justThere` might be more consistant. Having `catThere` and `catHere` would be great too :-)

**Comment by maxigit** [comment]
I've done a PR
