### ISSUE TITLE
Align laws are insufficient

### ISSUE THREAD

**Issue by viercc** [isomorphism/these#96]
I find the `Align` laws are insufficient. The current laws

```
(`align` nil) = fmap This
(nil `align`) = fmap That
join align = fmap (join These)
align (f <$> x) (g <$> y) = bimap f g <$> align x y
alignWith f a b = f <$> align a b
```

Do not eliminate this unwanted implementation ~for `[]`~ for `Map k`.

``` haskell
align x y
   | Map.null y = This <$> x
   | Map.null x = That <$> y
   | otherwise = Map.intersectionWith These x y
```

(Edited to clarify the relation between this counterexample and argument below)

---

One idea is to employ [Filterable](http://hackage.haskell.org/package/witherable-0.3/docs/Data-Witherable.html#t:Filterable) as a superclass, and include a law

``` haskell
align (mapMaybe f x) (mapMaybe g y) = mapMaybe (productMaybe f g)  (align x y)
  where
     productMaybe :: (a -> Maybe a') -> (b -> Maybe b') -> These a b -> Maybe (These a' b')
     productMaybe f g (This a) = This <$> f a
     productMaybe f g (That b) = That <$> g b
     productMaybe f g (These a b) = alignMaybe (f a) (g b)
     
     alignMaybe :: Maybe a -> Maybe b -> Maybe (These a b)
```

This law eliminates the counterexample above. Also, it matches the explanation given in the doc: `Align` is lax monoidal functor w.r.t `Kleisli Maybe`'s cartesian monoidal structure.

But there is a problem. `[]` is not a lawful instance anymore. This is probably unacceptable.

**Comment by phadej** [comment]
Ok. This issue makes total issues about laws overflow the threshold, so I promise that during 2019 I'll figure the CT between the laws and blog about them and (hopefully) make some decisions. So I don't promise any quick resolution, as I want to be sure, and no-one convinced me enough yet.

My counterexample is that `NonEmpty` has reasonable `align`, but current structure of this lib doesn't allow the instance, neither relying on `Filterable` makes it possible.

**Comment by viercc** [comment]
I'm glad to hear it'll be seriously worked on! I'll put other law-related issues here. I hope they'll help.

* I'm very novice in CT, but I think "lax monoidal w.r.t. Kleisli Maybe" thing only holds for maps (`Map k`, `IntMap`, `Maybe`) and not correct for sequences (`[]`, `Vector`, etc.) "functor from Kleisli Maybe to Hask" is exactly what `Filterable` is, and the law based on `Filterable` makes sequences miserable.

* `Monad m => Align (Stream m)` instance doesn't satisfy "idempotence law" `join align = fmap (join These)` as it duplicates monadic effect in LHS but RHS does not.

* I was about to propose `instance (Monoid a) => Align (Const a)`, but it also doesn't satisfy idempotence.

* I think it's safe to have "associativity law"
  
  ``` haskell
  align (align x y) z = assoc <$> align x (align y z)
    where
      assoc :: These a (These b c) -> These (These a b) c
      assoc = _
  ```

* "Commutativity law" is one of the candidates (but `Stream m` can't take it.)

  ``` haskell
  align x y = swap <$> align y x
    where swap :: These a b -> These b a
  ```

* The first counterexample I put, unwanted `align`, seems to satisfy both associativity and commutativity. It's surprisingly hard to eliminate by law.

**Comment by phadej** [comment]
How `Stream m` breaks on commutativity?

**Comment by phadej** [comment]
About the `Map` example. I see how it breaks *associativity*, but imagine we had an `Align` which doesn't have `nil`. Then sole `Map.intersectionWith These` would satisfy all these laws.

I.e. what we are missing is some way to say, that all elements in input containers are present in the `align`ed version, i.e. we *could* inverse `align`. Yet hypothetical

```
unalign' :: f (These a b) -> (f a, f b)
```

cannot be total for `f = NonEmpty` (but it would be total for all results of `align`!).

**Comment by viercc** [comment]
`unalign'` can't be implemented for this hypothetical instance. Although whether this should be an instance or not is subject to the discussion.

```
instance (JoinSemiLattice a) => Align (Const a) where
    Const a `align` Const b = Const (a \/ b)
```

The post I made [at Reddit](https://www.reddit.com/r/haskell/comments/abd75b/whats_this_something_is_to_lattice_as_applicative/) [(code)](https://github.com/viercc/kitchen-sink-hs/blob/master/src/LatticeLike.hs) is another way to treat it. Given a sensible `zip` operation, I think `align` which satisfies `LatticeLike` laws is also sensible (because they must be in a "dual"-ish relation.) `align = Map.intersectionWith These` will fail at `LatticeLike` law when combined with `zip = Map.intersectionWith (,)`.

This still doesn't determine one's instance uniquely, but I think that's OK.

**Comment by phadej** [comment]
See https://github.com/isomorphism/these/pull/100

If we can assume `Foldable f`, we can say:

```haskell
            toList xs === toListOf (folded . here) xys
            .&&.
            toList ys === toListOf (folded . there) xys
```

which is kind of asking for `Filterable`, but without (i.e. not a problem for `NonEmpty`)

**Comment by viercc** [comment]
I made an example which satisfies your sixth law and is idempotent, associative, commutative, but feels unnatural. Probably I'm too pedantic and the fact I have to make up this contrived example shows its practically sufficient.

``` haskell
newtype R a = Nest [[a]]
  deriving (Show, Eq, Functor, Foldable)

instance Align R where
  align (Nest ass) (Nest bss) =
    if shape ass == shape bss
      then Nest $ zipWith (zipWith These) ass bss
      else Nest [align (concat ass) (concat bss)]
    where
      shape = fmap (() <$)
```

**Comment by viercc** [comment]
Here's [said `LatticeLike R`](https://github.com/viercc/kitchen-sink-hs/blob/12d67c41e6a92629a31704379319196aa4be61b2/src/LatticeLike.hs#L321)

Your `Foldable` based solution seems perfect to current knowledge.
It is somewhat "loose" law that allows things like `R`, but so `LatticeLike` is.

**Comment by phadej** [comment]
I added assoc and toList laws. Will make a release soon.
